name: Publish
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: source

    - name: install system deps
      run: sudo apt-get install build-essential libcurl4-gnutls-dev ruby-full

    - name: build janet
      run: |
        git clone --depth 1 --branch v1.12.2 https://github.com/janet-lang/janet.git /tmp/janet
        cd /tmp/janet
        sudo make all test install

    - name: install janet deps
      run: sudo jpm deps

    - name: generate html
      run: |
        janet hn/import.janet
        janet reddit/import.janet
        ruby clojureverse/import.rb
        janet stackoverflow/import.janet
        janet version/import.janet
        janet render.janet
        mkdir -p dist
        cp index.html dist/index.html
        cp about.html dist/about.html
        cp css/*.css dist/
        rm index.html

    - name: publish latest
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git fetch
        git checkout master
        cp -r dist/* .
        rm -r dist
        git add -A
        git commit -m "Update"
        git push
